### ISSUE TITLE
crypto++ breaks Advisory generation

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#107]
Generating an Advisory for crypto++ breaks the Advisory generation since it has "++" in it's pkgname.

```
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 391-804-032
127.0.0.1 - - [02/Feb/2018 16:21:46] "GET /ASA-201802-1/generate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1518, in handle_user_exception
    return handler(e)
  File "/home/jelle/projects/arch-security-tracker/tracker/view/error.py", line 27, in wrapped
    return func(*args, **kwargs)
  File "/home/jelle/projects/arch-security-tracker/tracker/view/error.py", line 65, in internal_error
    raise e
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jelle/projects/arch-security-tracker/tracker/view/show.py", line 561, in show_generated_advisory
    raw_asa = advisory_extend_html(raw_asa, issues, package)
  File "/home/jelle/projects/arch-security-tracker/tracker/advisory.py", line 80, in advisory_extend_html
    advisory = sub('({}) '.format(package.pkgname), '<a href="/package/{0}">\g<1></a> '.format(package.pkgname), advisory, flags=IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 8
127.0.0.1 - - [02/Feb/2018 16:21:46] "GET /ASA-201802-1/generate?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
```

**Comment by jelly** [comment]
https://github.com/jelly/arch-security-tracker/tree/test_crypto%2B%2B Testcase here.
