### ISSUE TITLE
Package introduced in [testing]/[community-testing] without being in stable repos yet causes an exception

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#140]
```
Dec 06 11:29:00 apollo make[3189]:   -> Querying alpm database...done
Dec 06 11:29:00 apollo make[3189]:   -> Latest package: deepin-qt5dxcb-plugin 1.1.15-2 Thu Dec  6 10:28:37 2018
Dec 06 11:29:00 apollo make[3189]:   -> Updating database cache...done
Dec 06 11:29:00 apollo make[3189]: Updating group status...Traceback (most recent call last):
Dec 06 11:29:00 apollo make[3189]:   File "./trackerctl", line 5, in <module>
Dec 06 11:29:00 apollo make[3189]:     cli.main()
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 557, in main
Dec 06 11:29:00 apollo make[3189]:     return super(FlaskGroup, self).main(*args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
Dec 06 11:29:00 apollo make[3189]:     rv = self.invoke(ctx)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
Dec 06 11:29:00 apollo make[3189]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
Dec 06 11:29:00 apollo make[3189]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
Dec 06 11:29:00 apollo make[3189]:     return ctx.invoke(self.callback, **ctx.params)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Dec 06 11:29:00 apollo make[3189]:     return callback(*args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Dec 06 11:29:00 apollo make[3189]:     return f(get_current_context(), *args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
Dec 06 11:29:00 apollo make[3189]:     return __ctx.invoke(f, *args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Dec 06 11:29:00 apollo make[3189]:     return callback(*args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Dec 06 11:29:00 apollo make[3189]:     return f(get_current_context(), *args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/srv/http/security-tracker/tracker/cli/update.py", line 45, in env
Dec 06 11:29:00 apollo make[3189]:     ctx.invoke(group)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Dec 06 11:29:00 apollo make[3189]:     return callback(*args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Dec 06 11:29:00 apollo make[3189]:     return f(get_current_context(), *args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
Dec 06 11:29:00 apollo make[3189]:     return __ctx.invoke(f, *args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Dec 06 11:29:00 apollo make[3189]:     return callback(*args, **kwargs)
Dec 06 11:29:00 apollo make[3189]:   File "/srv/http/security-tracker/tracker/cli/update.py", line 58, in group
Dec 06 11:29:00 apollo make[3189]:     updated = update_group_status()
Dec 06 11:29:00 apollo make[3189]:   File "/srv/http/security-tracker/tracker/maintenance.py", line 27, in update_group_status
Dec 06 11:29:00 apollo make[3189]:     new_status = affected_to_status(status_to_affected(group.status), pkgnames[0], group.fixed)
Dec 06 11:29:00 apollo make[3189]:   File "/srv/http/security-tracker/tracker/model/enum.py", line 171, in affected_to_status
Dec 06 11:29:00 apollo make[3189]:     latest_non_testing = non_testing[0]
Dec 06 11:29:00 apollo make[3189]: IndexError: list index out of range
Dec 06 11:29:00 apollo make[3189]: make: *** [Makefile:23: update] Error 1

```

**Comment by jelly** [comment]
Can't reproduce the issue when using the archive.archlinux.org mirror from 6 December, nor when adding a local "testing" repository with a package which is not in our repos yet.
