### ISSUE TITLE
Updating the repos with a broken package fails

### ISSUE THREAD

**Issue by jelly** [archlinux/arch-security-tracker#155]
```
Apr 23 14:42:31 apollo make[22186]: Updating package cache...
Apr 23 14:42:31 apollo make[22186]:   -> Querying alpm database...done
Apr 23 14:42:31 apollo make[22186]:   -> Latest package: ruby-msgpack 1.2.10-1 Tue Apr 23 14:28:52 2019
Apr 23 14:42:32 apollo make[22186]:   -> Updating database cache...Traceback (most recent call last):
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
Apr 23 14:42:32 apollo make[22186]:     cursor, statement, parameters, context
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Apr 23 14:42:32 apollo make[22186]:     cursor.execute(statement, parameters)
Apr 23 14:42:32 apollo make[22186]: sqlite3.IntegrityError: NOT NULL constraint failed: package.arch
Apr 23 14:42:32 apollo make[22186]: The above exception was the direct cause of the following exception:
Apr 23 14:42:32 apollo make[22186]: Traceback (most recent call last):
Apr 23 14:42:32 apollo make[22186]:   File "./trackerctl", line 5, in <module>
Apr 23 14:42:32 apollo make[22186]:     cli.main()
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 557, in main
Apr 23 14:42:32 apollo make[22186]:     return super(FlaskGroup, self).main(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
Apr 23 14:42:32 apollo make[22186]:     rv = self.invoke(ctx)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
Apr 23 14:42:32 apollo make[22186]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
Apr 23 14:42:32 apollo make[22186]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
Apr 23 14:42:32 apollo make[22186]:     return ctx.invoke(self.callback, **ctx.params)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Apr 23 14:42:32 apollo make[22186]:     return callback(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Apr 23 14:42:32 apollo make[22186]:     return f(get_current_context(), *args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
Apr 23 14:42:32 apollo make[22186]:     return __ctx.invoke(f, *args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Apr 23 14:42:32 apollo make[22186]:     return callback(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Apr 23 14:42:32 apollo make[22186]:     return f(get_current_context(), *args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/srv/http/security-tracker/tracker/cli/update.py", line 44, in env
Apr 23 14:42:32 apollo make[22186]:     ctx.invoke(cache)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Apr 23 14:42:32 apollo make[22186]:     return callback(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
Apr 23 14:42:32 apollo make[22186]:     return f(get_current_context(), *args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
Apr 23 14:42:32 apollo make[22186]:     return __ctx.invoke(f, *args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Apr 23 14:42:32 apollo make[22186]:     return callback(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/srv/http/security-tracker/tracker/cli/update.py", line 35, in cache
Apr 23 14:42:32 apollo make[22186]:     update_package_cache()
Apr 23 14:42:32 apollo make[22186]:   File "/srv/http/security-tracker/tracker/maintenance.py", line 94, in update_package_cache
Apr 23 14:42:32 apollo make[22186]:     db.session.bulk_insert_mappings(Package, new_packages)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
Apr 23 14:42:32 apollo make[22186]:     return getattr(self.registry(), name)(*args, **kwargs)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2790, in bulk_insert_mappings
Apr 23 14:42:32 apollo make[22186]:     render_nulls,
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2880, in _bulk_save_mappings
Apr 23 14:42:32 apollo make[22186]:     transaction.rollback(_capture_exception=True)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
Apr 23 14:42:32 apollo make[22186]:     compat.reraise(exc_type, exc_value, exc_tb)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
Apr 23 14:42:32 apollo make[22186]:     raise value
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2874, in _bulk_save_mappings
Apr 23 14:42:32 apollo make[22186]:     render_nulls,
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
Apr 23 14:42:32 apollo make[22186]:     bookkeeping=return_defaults,
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1066, in _emit_insert_statements
Apr 23 14:42:32 apollo make[22186]:     c = cached_connections[connection].execute(statement, multiparams)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
Apr 23 14:42:32 apollo make[22186]:     return meth(self, multiparams, params)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
Apr 23 14:42:32 apollo make[22186]:     return connection._execute_clauseelement(self, multiparams, params)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
Apr 23 14:42:32 apollo make[22186]:     distilled_params,
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
Apr 23 14:42:32 apollo make[22186]:     e, statement, parameters, cursor, context
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
Apr 23 14:42:32 apollo make[22186]:     util.raise_from_cause(sqlalchemy_exception, exc_info)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
Apr 23 14:42:32 apollo make[22186]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
Apr 23 14:42:32 apollo make[22186]:     raise value.with_traceback(tb)
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
Apr 23 14:42:32 apollo make[22186]:     cursor, statement, parameters, context
Apr 23 14:42:32 apollo make[22186]:   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Apr 23 14:42:32 apollo make[22186]:     cursor.execute(statement, parameters)
Apr 23 14:42:32 apollo make[22186]: sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: package.arch
Apr 23 14:42:32 apollo make[22186]: [SQL: INSERT INTO package (name, base, version, "database", builddate) VALUES (?, ?, ?, ?, ?)]
Apr 23 14:42:32 apollo make[22186]: [parameters: ('metasploit', 'metasploit', '5.0.9-1', 'community', 0)]
Apr 23 14:42:32 apollo make[22186]: (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by jelly** [comment]
Not reproducible with the archive package, but it was corrupted on our mirror somehow (desc was not readable).

https://archive.archlinux.org/packages/m/metasploit/metasploit-5.0.9-1-x86_64.pkg.tar.xz
