### ISSUE TITLE
trackerctl setup user raises error

### ISSUE THREAD

**Issue by ekardnam** [archlinux/arch-security-tracker#192]
Good evening,
running `trackerctl setup user --username luca --email lucabertozzi.pub@gmail.com --password aaaaaaaaaaaaa` fails after setting the role to any value with this message
```
arch-security-tracker on  add-footer [!] via .virtualenv took 2s 
➜ ./trackerctl setup user --username luca --email lucabertozzi.pub@gmail.com  --password aaaaaaaaaaaaaaaa
Role (administrator, security_team, reporter, guest) [reporter]: 
Traceback (most recent call last):
  File "/home/neutrin0/Repos/arch-security-tracker/./trackerctl", line 5, in <module>
    cli.main()
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/core.py", line 2307, in type_cast_value
    return convert(value)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/home/neutrin0/Repos/arch-security-tracker/.virtualenv/lib/python3.9/site-packages/click/types.py", line 284, in convert
    if normed_value in normed_choices:
TypeError: unhashable type: 'UserRole'

```

I already have a fix for this and make a PR. Basically the click option for role returns a value of the Enum UserRole which is not hashable. Two possible solutions are possible: either implementing `__hash__` for the Enum or just making it return a string and converting to the Enum value after which is the one i have done.

**Comment by jelly** [comment]
Fied in da69dabf07fa033434996bb6a41207696a8a5058
